### PR TITLE
Fixed RCS use Throthle feature

### PR DESCRIPTION
**Pull request by sswelm**
The intention of Throttle feature is to send the ship forward yes? not size way, because what it did.

### CODE REVIEW

**Comment by NathanKell** [comment]
Odd. The ship's Y axis is thrust-forward, so I'm confused that inputlinear.X would in fact be the forward/back axis.

**Comment by Starwaster** [comment]
Checked this out personally, and the nature of the throttle issue is that it is using the world axes. Input needs to be remapped, not have its axis changed. 

Sorry but all your change is doing is affecting which world axis is being used. (instead of remapping to vehicle local axes)

**Comment by NathanKell** [comment]
Yep, should be vessel Y. I'll do that and roll out a release with @Starwaster's MJ fix.

**Comment by NathanKell** [comment]
@sswelm thanks for bringing this to my attention; the new release should have it fixed. :)

**Comment by sswelm** [comment]
Hreat to see it was fixed the correct way. I just tried to make it function at the launch pad LOL

**Pull request closed without merging**
